import type { NextPage } from 'next'
import Head from 'next/head'
import { ToDoContainer } from "../components/ToDoContainer";
import {useEffect, useState} from "react";

const Home: NextPage = () => {
    const [isLoaded, setIsLoaded] = useState(false);

    useEffect(() => {
        setIsLoaded(true);
    }, []);

    return (
    <div style={{background: "linear-gradient(0.125turn, #e66465, #9198e5)",
      height: "100vh",
      display: "flex",
      justifyContent: "center",
    }}>
      <Head>
        <title>TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {isLoaded && <ToDoContainer />}
    </div>
    )
}

export default Home
